### ISSUE TITLE
Use with Google fonts?

### ISSUE THREAD

**Issue by vishy93** [CD1212/jQuery-Font-Chooser#9]
Would this work with google fonts, so fonts that may potentially not be installed on the device?

**Comment by CD1212** [comment]
Hi @vishy93, thanks for your question. Yes it should work fine with Google fonts. Any font accessible to CSS would work, whether Google font or loaded with `@font-face` etc.

**Comment by vishy93** [comment]
Hi @CD1212 is there a way to adapt it to load the fonts on load ?

**Comment by CD1212** [comment]
I would have thought this could work in the same way as initialising the plugin normally. You could use https://github.com/typekit/webfontloader to load Google fonts through JS and then initialise the font selector after, if the fonts needed were in some way dynamic.

**Comment by vishy93** [comment]
I have  got this to work using the web font loader but is there a way to get index the one selected? so when user selects one of the options in the widget a correpndong select will likewise get updated?
